// Generates the StoxWork logo family from one source of truth.
//   - the mark is drawn here: one continuous S whose top stroke kicks up like a
//     price tick, set on the brand's gold tile ("stocks, put to work")
//   - the wordmark is outlined from the brand font so it needs no webfont
//   - PNG exports are rendered from the same SVG
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { Resvg } from '@resvg/resvg-js'
import opentype from 'opentype.js'

const ROOT = path.resolve(import.meta.dirname, '..')
// Schibsted Grotesk instanced at wght=600 from the variable font (OFL, see fonts/OFL.txt)
const FONT = path.join(import.meta.dirname, 'fonts/SchibstedGrotesk-600.ttf')

const INK = '#0e0f11'
const GOLD = '#f2c55c'
const GOLD_DEEP = '#a97521'

/* ---- the mark: 40x40 ------------------------------------------------------ */
// The S is a single stroke: bottom bar, right bowl, spine, left bowl, top bar,
// then a 40-degree kick up and to the right. Stroke weight matches the UI's
// heavier icon weight scaled to the tile.
export const S_PATH =
  'M11 31.7H24A4.5 4.5 0 0 0 24 22.7H16A4.5 4.5 0 0 1 16 13.7H23.5L29.5 8.2'

const markPaths = (tile, stroke) => `
  <rect width="40" height="40" rx="10" fill="${tile}"/>
  <path d="${S_PATH}" fill="none" stroke="${stroke}" stroke-width="4.4" stroke-linecap="round" stroke-linejoin="round"/>`

/* ---- the wordmark: real glyph outlines ------------------------------------ */
const font = opentype.parse(readFileSync(FONT).buffer)
const SIZE = 100
const TRACK = -0.012 * SIZE

function wordmark(text) {
  let x = 0
  const parts = []
  for (const ch of text) {
    const glyph = font.charToGlyph(ch)
    parts.push(glyph.getPath(x, 0, SIZE).toPathData(3))
    x += (glyph.advanceWidth / font.unitsPerEm) * SIZE + TRACK
  }
  const capHeight = (font.tables.os2.sCapHeight / font.unitsPerEm) * SIZE
  return { d: parts.join(' '), width: x - TRACK, height: capHeight }
}

const wm = wordmark('StoxWork')

/* ---- horizontal lockup ---------------------------------------------------- */
const MARK = 40
const GAP = 12
const WM_SCALE = 0.6
const wmW = wm.width * WM_SCALE
const wmH = wm.height * WM_SCALE
const LOCKUP_W = MARK + GAP + wmW

const lockup = (tile, stroke, word) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${LOCKUP_W.toFixed(2)} ${MARK}" fill="none">
  ${markPaths(tile, stroke)}
  <g transform="translate(${MARK + GAP} ${((MARK + wmH) / 2).toFixed(2)}) scale(${WM_SCALE})">
    <path d="${wm.d}" fill="${word}"/>
  </g>
</svg>`

const markOnly = (tile, stroke) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40" fill="none">${markPaths(tile, stroke)}
</svg>`

mkdirSync(path.join(ROOT, 'public/brand'), { recursive: true })
const out = (rel, data) => {
  writeFileSync(path.join(ROOT, rel), data)
  console.log('wrote', rel)
}

out('public/brand/logo.svg', lockup(GOLD, INK, '#ffffff'))
out('public/brand/logo-light.svg', lockup(GOLD_DEEP, '#ffffff', INK))
out('public/brand/mark.svg', markOnly(GOLD, INK))
out('public/favicon.svg', markOnly(GOLD, INK))

/* ---- 500x500 PNG exports: stacked lockup, 12% padding, centred ----------- */
const STACK_MARK = 300
const STACK_GAP = 64
const STACK_WM_SCALE = 1.4
const stackWmW = wm.width * STACK_WM_SCALE
const stackWmH = wm.height * STACK_WM_SCALE
const STACK_W = Math.max(STACK_MARK, stackWmW)
const STACK_H = STACK_MARK + STACK_GAP + stackWmH

function square(bg) {
  const inner = 500 - 0.12 * 500 * 2
  const scale = Math.min(inner / STACK_W, inner / STACK_H)
  const w = STACK_W * scale
  const h = STACK_H * scale
  return `<svg xmlns="http://www.w3.org/2000/svg" width="500" height="500" viewBox="0 0 500 500" fill="none">
  ${bg ? `<rect width="500" height="500" fill="${bg}"/>` : ''}
  <g transform="translate(${((500 - w) / 2).toFixed(2)} ${((500 - h) / 2).toFixed(2)}) scale(${scale.toFixed(4)})">
    <g transform="translate(${((STACK_W - STACK_MARK) / 2).toFixed(2)} 0) scale(${(STACK_MARK / 40).toFixed(4)})">
      ${markPaths(GOLD, INK)}
    </g>
    <g transform="translate(${((STACK_W - stackWmW) / 2).toFixed(2)} ${(STACK_MARK + STACK_GAP + stackWmH).toFixed(2)}) scale(${STACK_WM_SCALE})">
      <path d="${wm.d}" fill="#ffffff"/>
    </g>
  </g>
</svg>`
}

for (const [file, bg] of [
  ['public/brand/logo-500.png', INK],
  ['public/brand/logo-500-transparent.png', null],
]) {
  const png = new Resvg(square(bg), { fitTo: { mode: 'width', value: 500 } }).render().asPng()
  writeFileSync(path.join(ROOT, file), png)
  console.log('wrote', file, png.length, 'bytes')
}

/* ---- emit the mark + outlined wordmark for the React logo component ------- */
out(
  'src/components/brand/wordmark.ts',
  `// GENERATED by scripts/build-logo.mjs. Do not edit by hand.
// "StoxWork" outlined from Schibsted Grotesk (OFL) at wght 600, tracking -0.012em,
// so the wordmark renders identically with or without the webfont.
export const WORDMARK_PATH =
  '${wm.d}'

/** Advance width and cap height of the outlined run, in the same user units. */
export const WORDMARK_WIDTH = ${wm.width.toFixed(2)}
export const WORDMARK_CAP = ${wm.height.toFixed(2)}

/** The mark's single S stroke, on a 40u tile. */
export const MARK_S_PATH = '${S_PATH}'
`,
)
